from dataclasses import dataclass
from pathlib import Path
from subprocess import Popen

@dataclass
class PGliteConfig:
    timeout: int = 30
    cleanup_on_exit: bool = True
    log_level: str = "INFO"
    socket_path: str = ""
    work_dir: Path | None = None
    node_modules_check: bool = True
    auto_install_deps: bool = True
    extensions: list[str] | None = None
    node_options: str | None = None
    use_tcp: bool = False
    tcp_host: str = "127.0.0.1"
    tcp_port: int = 5432

    def get_asyncpg_uri(self) -> str: ...
    def get_psycopg_uri(self) -> str: ...
    def get_dsn(self) -> str: ...

class PGliteManager:
    process: Popen[str] | None
    def __init__(self, config: PGliteConfig | None = None) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def restart(self) -> None: ...
    def is_running(self) -> bool: ...
    def wait_for_ready(self, max_retries: int = 15, delay: float = 1.0) -> bool: ...
    def get_asyncpg_uri(self) -> str: ...
    def get_dsn(self) -> str: ...
    def get_psycopg_uri(self) -> str: ...
    def get_connection_string(self) -> str: ...
