from typing import LiteralString

class node:
    kind: str
    # present on command, pipeline, list, word nodes
    parts: list[node]
    # present on word and assignment nodes
    word: str
    # present on compound nodes (subshells, group commands)
    list: list[node]
    # present on commandsubstitution and processsubstitution nodes
    command: node
    # present on operator nodes (&&, ||, ;)
    op: str
    # character position span
    pos: tuple[int, int]

    def __init__(self, **kwargs: object) -> None: ...
    def dump(self, indent: int = ...) -> LiteralString | str: ...
    def __repr__(self) -> LiteralString: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class nodevisitor:
    def visit(self, n: node) -> None: ...
    def visitnode(self, n: node) -> None: ...
    def visitnodeend(self, n: node) -> None: ...
    def visitoperator(self, n: node, op: str) -> None: ...
    def visitlist(self, n: node, parts: list[node]) -> None: ...
    def visitpipe(self, n: node, pipe: str) -> None: ...
    def visitpipeline(self, n: node, parts: list[node]) -> None: ...
    def visitcompound(
        self, n: node, list: list[node], redirects: list[node]
    ) -> None: ...
    def visitif(self, n: node, parts: list[node]) -> None: ...
    def visitfor(self, n: node, parts: list[node]) -> None: ...
    def visitwhile(self, n: node, parts: list[node]) -> None: ...
    def visituntil(self, n: node, parts: list[node]) -> None: ...
    def visitcommand(self, n: node, parts: list[node]) -> None: ...
    def visitfunction(
        self, n: node, name: node, body: node, parts: list[node]
    ) -> None: ...
    def visitword(self, n: node, word: str) -> None: ...
    def visitassignment(self, n: node, word: str) -> None: ...
    def visitreservedword(self, n: node, word: str) -> None: ...
    def visitparameter(self, n: node, value: str) -> None: ...
    def visittilde(self, n: node, value: str) -> None: ...
    def visitredirect(
        self, n: node, input: int | None, type: str, output: node, heredoc: node | None
    ) -> None: ...
    def visitheredoc(self, n: node, value: str) -> None: ...
    def visitprocesssubstitution(self, n: node, command: node) -> None: ...
    def visitcommandsubstitution(self, n: node, command: node) -> None: ...

def findfirstkind(parts: list[node], kind: str) -> int: ...

class posconverter(nodevisitor):
    def __init__(self, string: str) -> None: ...
    def visitnode(self, n: node) -> None: ...

class posshifter(nodevisitor):
    def __init__(self, count: int) -> None: ...
    def visitnode(self, n: node) -> None: ...
