from collections.abc import Generator
from typing import Any

from bashlex import ast

tokens = ...
precedence = ...

def handleNotImplemented(p, type): ...
def handleAssert(p, test) -> None: ...
def p_inputunit(p) -> None: ...
def p_word_list(p) -> None: ...
def p_redirection_heredoc(p) -> None: ...
def p_redirection(p) -> None: ...
def p_simple_command_element(p) -> None: ...
def p_redirection_list(p) -> None: ...
def p_simple_command(p) -> None: ...
def p_command(p) -> None: ...
def p_shell_command(p) -> None: ...
def p_for_command(p) -> None: ...
def p_arith_for_command(p) -> None: ...
def p_select_command(p) -> None: ...
def p_case_command(p) -> None: ...
def p_function_def(p) -> None: ...
def p_function_body(p) -> None: ...
def p_subshell(p) -> None: ...
def p_coproc(p) -> None: ...
def p_if_command(p) -> None: ...
def p_group_command(p) -> None: ...
def p_arith_command(p) -> None: ...
def p_cond_command(p) -> None: ...
def p_elif_clause(p) -> None: ...
def p_case_clause(p) -> None: ...
def p_pattern_list(p) -> None: ...
def p_case_clause_sequence(p) -> None: ...
def p_pattern(p) -> None: ...
def p_list(p) -> None: ...
def p_compound_list(p) -> None: ...
def p_list0(p) -> None: ...
def p_list1(p) -> None: ...
def p_simple_list_terminator(p) -> None: ...
def p_list_terminator(p) -> None: ...
def p_newline_list(p) -> None: ...
def p_simple_list(p) -> None: ...
def p_simple_list1(p) -> None: ...
def p_pipeline_command(p) -> None: ...
def p_pipeline(p) -> None: ...
def p_timespec(p) -> None: ...
def p_empty(p) -> None: ...
def p_error(p): ...

yaccparser = ...

def get_correction_states() -> tuple[Any, Any]: ...
def get_correction_rightparen_states() -> tuple[Any, Any, Any]: ...

states = ...

def parsesingle(s, strictmode=..., expansionlimit=..., convertpos=...): ...
def parse(s, strictmode=..., expansionlimit=..., convertpos=...) -> list[Any]: ...
def split(s) -> Generator[Any, Any]: ...

class _parser:
    def __init__(
        self, s, strictmode=..., expansionlimit=..., tokenizerargs=...
    ) -> None: ...
    def parse(self): ...

class _endfinder(ast.nodevisitor):
    def __init__(self) -> None: ...
    def visitheredoc(self, node, value) -> None: ...
