from typing import Literal, LiteralString

def single_quote(s) -> str: ...
def double_quote(s): ...
def legal_number(s) -> bool: ...
def legal_identifier(name) -> None: ...
def removequotes(s, heredoc=..., doublequotes=...) -> LiteralString | Literal[""]: ...
