from collections.abc import Iterator
from typing import Any, Literal, LiteralString, Self

import enum

from bashlex import errors, flags

sh_syntaxtab = ...

class tokentype(enum.Enum):
    IF = ...
    THEN = ...
    ELSE = ...
    ELIF = ...
    FI = ...
    CASE = ...
    ESAC = ...
    FOR = ...
    SELECT = ...
    WHILE = ...
    UNTIL = ...
    DO = ...
    DONE = ...
    FUNCTION = ...
    COPROC = ...
    COND_START = ...
    COND_END = ...
    IN = ...
    BANG = ...
    TIME = ...
    TIMEOPT = ...
    TIMEIGN = ...
    WORD = ...
    ASSIGNMENT_WORD = ...
    REDIR_WORD = ...
    NUMBER = ...
    ARITH_CMD = ...
    ARITH_FOR_EXPRS = ...
    COND_CMD = ...
    AND_AND = ...
    OR_OR = ...
    GREATER_GREATER = ...
    LESS_LESS = ...
    LESS_AND = ...
    LESS_LESS_LESS = ...
    GREATER_AND = ...
    SEMI_SEMI = ...
    SEMI_AND = ...
    SEMI_SEMI_AND = ...
    LESS_LESS_MINUS = ...
    AND_GREATER = ...
    AND_GREATER_GREATER = ...
    LESS_GREATER = ...
    GREATER_BAR = ...
    BAR_AND = ...
    LEFT_CURLY = ...
    RIGHT_CURLY = ...
    EOF = ...
    LEFT_PAREN = ...
    RIGHT_PAREN = ...
    BAR = ...
    SEMICOLON = ...
    DASH = ...
    NEWLINE = ...
    LESS = ...
    GREATER = ...
    AMPERSAND = ...

_reserved = ...
valid_reserved_first_command = ...

class MatchedPairError(errors.ParsingError):
    def __init__(self, startline, message, tokenizer) -> None: ...

wordflags = flags.word
parserflags = flags.parser

class token:
    def __init__(self, type_, value, pos=..., flags=...) -> None: ...
    @property
    def type(
        self,
    ) -> (
        Literal[
            "$end",
            IF,
            THEN,
            ELSE,
            ELIF,
            FI,
            CASE,
            ESAC,
            FOR,
            SELECT,
            WHILE,
            UNTIL,
            DO,
            DONE,
            FUNCTION,
            COPROC,
            COND_START,
            COND_END,
            IN,
            BANG,
            TIME,
            TIMEOPT,
            TIMEIGN,
            WORD,
            ASSIGNMENT_WORD,
            REDIR_WORD,
            NUMBER,
            ARITH_CMD,
            ARITH_FOR_EXPRS,
            COND_CMD,
            AND_AND,
            OR_OR,
            GREATER_GREATER,
            LESS_LESS,
            LESS_AND,
            LESS_LESS_LESS,
            GREATER_AND,
            SEMI_SEMI,
            SEMI_AND,
            SEMI_SEMI_AND,
            LESS_LESS_MINUS,
            AND_GREATER,
            AND_GREATER_GREATER,
            LESS_GREATER,
            GREATER_BAR,
            BAR_AND,
            LEFT_CURLY,
            RIGHT_CURLY,
            LEFT_PAREN,
            RIGHT_PAREN,
            BAR,
            SEMICOLON,
            DASH,
            NEWLINE,
            LESS,
            GREATER,
            AMPERSAND,
        ]
        | None
    ): ...
    def __nonzero__(self) -> bool: ...

    __bool__ = ...
    def __eq__(self, other) -> bool: ...
    def __repr__(self): ...
    def nopos(self) -> Self: ...

eoftoken = ...

class tokenizer:
    def __init__(
        self,
        s,
        parserstate,
        strictmode=...,
        eoftoken=...,
        lastreadtoken=...,
        tokenbeforethat=...,
        twotokensago=...,
    ) -> None: ...
    @property
    def source(self) -> Any: ...
    def __iter__(self) -> Iterator[token | Any]: ...
    def token(self) -> token: ...
    def readline(self, removequotenewline) -> LiteralString | None: ...
