from collections.abc import Iterator, Mapping, MutableSet
from typing import Any, Self

class typedset(MutableSet):
    def __init__(self, type_, iterable=...) -> None: ...
    def add(self, value) -> None: ...
    def discard(self, value) -> None: ...
    def __contains__(self, value) -> bool: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __and__(self, value) -> set[Any]: ...
    def __or__(self, value) -> set[Any]: ...
    def __ior__(self, value) -> Self: ...

class frozendict(Mapping):
    def __init__(self, *args, **kwargs) -> None: ...
    def __getitem__(self, key): ...
    def copy(self, **add_or_replace) -> frozendict: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
