from typing import Any, Literal, LiteralString, Self

yaccdebug = ...
debug_file = ...
error_count = ...
resultlimit = ...
MAXINT = ...

class PlyLogger:
    def __init__(self, f) -> None: ...
    def debug(self, msg, *args, **kwargs) -> None: ...

    info = ...
    def warning(self, msg, *args, **kwargs) -> None: ...
    def error(self, msg, *args, **kwargs) -> None: ...

    critical = ...

class NullLogger:
    def __getattribute__(self, name) -> Self: ...
    def __call__(self, *args, **kwargs) -> Self: ...

class YaccError(Exception): ...
class YaccAccept(Exception): ...

def format_result(r) -> str: ...
def format_stack_entry(r) -> str: ...

class YaccSymbol: ...

class YaccProduction:
    def __init__(self, s, stack=...) -> None: ...
    def __getitem__(self, n) -> list[Any]: ...
    def __setitem__(self, n, v) -> None: ...
    def __getslice__(self, i, j) -> list[Any]: ...
    def __len__(self) -> int: ...
    def lineno(self, n) -> int: ...
    def set_lineno(self, n, lineno) -> None: ...
    def linespan(self, n) -> tuple[Any | int, Any | int]: ...
    def lexpos(self, n) -> int: ...
    def endlexpos(self, n) -> int: ...
    def set_lexpos(self, n, lexpos) -> None: ...
    def lexspan(self, n) -> tuple[Any | int, Any | int]: ...
    def error(self): ...
    def accept(self): ...

class LRParser:
    def __init__(self, lrtab, errorf) -> None: ...
    def errok(self) -> None: ...
    def restart(self) -> None: ...
    def set_defaulted_states(self) -> None: ...
    def disable_defaulted_states(self) -> None: ...
    def parse(self, input=..., lexer=..., debug=..., tracking=..., context=...): ...

_is_identifier = ...

class Production:
    reduced = ...
    def __init__(
        self, number, name, prod, precedence=..., func=..., file=..., line=...
    ) -> None: ...
    def __len__(self) -> int: ...
    def __nonzero__(self) -> Literal[1]: ...
    def __getitem__(self, index): ...
    def lr_item(self, n) -> LRItem | None: ...
    def bind(self, pdict) -> None: ...

class LRItem:
    def __init__(self, p, n) -> None: ...

def rightmost_terminal(symbols, terminals) -> None: ...

class GrammarError(YaccError): ...

class Grammar:
    def __init__(self, terminals) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index): ...
    def set_precedence(self, term, assoc, level) -> None: ...
    def add_production(self, prodname, syms, func=..., file=..., line=...) -> None: ...
    def set_start(self, start=...) -> None: ...
    def find_unreachable(self) -> list[Any]: ...
    def infinite_cycles(self) -> list[Any]: ...
    def undefined_symbols(self) -> list[Any]: ...
    def unused_terminals(self) -> list[Any]: ...
    def unused_rules(self) -> list[Any]: ...
    def unused_precedence(self) -> list[Any]: ...
    def compute_first(self) -> dict[Any, Any]: ...
    def compute_follow(self, start=...) -> dict[Any, Any]: ...
    def build_lritems(self) -> None: ...

def digraph(X, R, FP) -> dict[Any, Any]: ...
def traverse(x, N, stack, F, X, R, FP) -> None: ...

class LALRError(YaccError): ...

class LRTable:
    def __init__(self, grammar, log=...) -> None: ...
    def bind_callables(self, pdict) -> None: ...
    def lr0_closure(self, I): ...
    def lr0_goto(self, I, x) -> list[Any] | None: ...
    def lr0_items(self) -> list[list[Any]]: ...
    def compute_nullable_nonterminals(self) -> set[Any]: ...
    def find_nonterminal_transitions(self, C) -> list[Any]: ...
    def dr_relation(self, C, trans, nullable) -> list[Any]: ...
    def reads_relation(self, C, trans, empty) -> list[Any]: ...
    def compute_lookback_includes(
        self, C, trans, nullable
    ) -> tuple[dict[Any, Any], dict[Any, Any]]: ...
    def compute_read_sets(self, C, ntrans, nullable) -> dict[Any, Any]: ...
    def compute_follow_sets(self, ntrans, readsets, inclsets) -> dict[Any, Any]: ...
    def add_lookaheads(self, lookbacks, followset) -> None: ...
    def add_lalr_lookaheads(self, C) -> None: ...
    def lr_parse_table(self) -> None: ...

def get_caller_module_dict(levels) -> dict[str, Any]: ...
def parse_grammar(doc, file, line) -> list[Any]: ...

class ParserReflect:
    def __init__(self, pdict, log=...) -> None: ...
    def get_all(self) -> None: ...
    def validate_all(self) -> bool: ...
    def signature(self) -> LiteralString: ...
    def validate_modules(self) -> None: ...
    def get_start(self) -> None: ...
    def validate_start(self) -> None: ...
    def get_error_func(self) -> None: ...
    def validate_error_func(self) -> None: ...
    def get_tokens(self) -> None: ...
    def validate_tokens(self) -> None: ...
    def get_precedence(self) -> None: ...
    def validate_precedence(self) -> None: ...
    def get_pfunctions(self) -> None: ...
    def validate_pfunctions(self) -> None: ...

def yacc(
    method=...,
    debug=...,
    module=...,
    start=...,
    check_recursion=...,
    optimize=...,
    write_tables=...,
    debugfile=...,
    outputdir=...,
    debuglog=...,
    errorlog=...,
    picklefile=...,
): ...
