from collections.abc import (
    AsyncIterable,
    AsyncIterator,
    Callable,
    Iterable,
    Iterator,
    Mapping,
)
from typing import Any, Self

import types

type URLTypes = URL | str
type _Primitive = str | int | float | bool | None
type QueryParamTypes = (
    QueryParams
    | Mapping[str, _Primitive | list[_Primitive]]
    | list[tuple[str, _Primitive]]
    | tuple[tuple[str, _Primitive], ...]
    | str
    | bytes
)
type HeaderTypes = (
    Headers
    | Mapping[str, str]
    | Mapping[bytes, bytes]
    | list[tuple[str, str]]
    | list[tuple[bytes, bytes]]
)
type CookieTypes = Cookies | dict[str, str] | list[tuple[str, str]]
type RequestContent = str | bytes | Iterable[bytes] | AsyncIterable[bytes]
type RequestData = Mapping[str, Any]
type RequestFiles = Mapping[str, Any] | list[tuple[str, Any]]
type AuthTypes = Auth | Callable[[Request], Request] | tuple[str | bytes, str | bytes]
type TimeoutTypes = float | None | tuple[float | None, ...] | Timeout
type ProxyTypes = URLTypes | Proxy
type RequestExtensions = Mapping[str, Any]
type ResponseExtensions = Mapping[str, Any]
type ResponseContent = str | bytes | Iterable[bytes] | AsyncIterable[bytes]
type VerifyTypes = str | bool | Any
type CertTypes = str | tuple[str, str | None] | tuple[str, str | None, str | None]

class UseClientDefault: ...

USE_CLIENT_DEFAULT: UseClientDefault

class URL:
    def __init__(self, url: URLTypes = ..., **kwargs: Any) -> None: ...
    @property
    def path(self) -> str: ...
    @property
    def query(self) -> bytes: ...
    @property
    def scheme(self) -> str: ...
    @property
    def host(self) -> str: ...
    @property
    def params(self) -> QueryParams: ...

class QueryParams:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def get_list(self, key: str) -> list[str]: ...
    def __getitem__(self, key: str) -> str: ...
    def __contains__(self, key: object) -> bool: ...

class Headers(Mapping[str, str]):
    def __init__(self, headers: HeaderTypes | None = ..., **kwargs: Any) -> None: ...
    def __getitem__(self, key: str) -> str: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

class Cookies(Mapping[str, str]):
    def __init__(self, cookies: CookieTypes | None = ...) -> None: ...
    def set(self, name: str, value: str, **kwargs: Any) -> None: ...
    def clear(self, **kwargs: Any) -> None: ...
    def __getitem__(self, name: str) -> str: ...
    def __setitem__(self, name: str, value: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

class Auth: ...

class AsyncByteStream:
    def __aiter__(self) -> AsyncIterator[bytes]: ...
    async def aclose(self) -> None: ...

class Timeout:
    def __init__(
        self,
        timeout: Any = ...,
        *,
        connect: float | None = ...,
        read: float | None = ...,
        write: float | None = ...,
        pool: float | None = ...,
    ) -> None: ...

class Limits:
    def __init__(
        self,
        *,
        max_connections: int | None = ...,
        max_keepalive_connections: int | None = ...,
        keepalive_expiry: float | None = ...,
    ) -> None: ...

class Proxy:
    def __init__(self, url: URLTypes, **kwargs: Any) -> None: ...

class Request:
    def __init__(self, method: str, url: URLTypes, **kwargs: Any) -> None: ...
    @property
    def method(self) -> str: ...
    @property
    def url(self) -> URL: ...
    @property
    def headers(self) -> Headers: ...
    @property
    def content(self) -> bytes: ...

class Response:
    def __init__(
        self,
        status_code: int,
        *,
        headers: HeaderTypes | None = ...,
        content: ResponseContent | None = ...,
        text: str | None = ...,
        html: str | None = ...,
        json: Any = ...,
        stream: Any = ...,
        request: Request | None = ...,
        extensions: ResponseExtensions | None = ...,
        history: list[Response] | None = ...,
        default_encoding: str | Callable[[bytes], str] = ...,
    ) -> None: ...
    @property
    def status_code(self) -> int: ...
    @property
    def headers(self) -> Headers: ...
    @property
    def cookies(self) -> Cookies: ...
    @property
    def text(self) -> str: ...
    @property
    def content(self) -> bytes: ...
    @property
    def url(self) -> URL: ...
    @property
    def request(self) -> Request: ...
    @property
    def encoding(self) -> str | None: ...
    @property
    def is_redirect(self) -> bool: ...
    @property
    def is_success(self) -> bool: ...
    @property
    def is_error(self) -> bool: ...
    @property
    def is_client_error(self) -> bool: ...
    @property
    def is_server_error(self) -> bool: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def elapsed(self) -> Any: ...
    @property
    def reason_phrase(self) -> str: ...
    def aiter_lines(self) -> AsyncIterator[str]: ...
    def iter_lines(self) -> Iterator[str]: ...
    def json(self, **kwargs: Any) -> Any: ...
    def raise_for_status(self) -> Response: ...
    def read(self) -> bytes: ...
    def iter_bytes(self, chunk_size: int | None = ...) -> Iterator[bytes]: ...
    async def aread(self) -> bytes: ...
    def aiter_bytes(self, chunk_size: int | None = ...) -> AsyncIterator[bytes]: ...

class BaseTransport:
    def handle_request(self, request: Request) -> Response: ...

class AsyncBaseTransport:
    async def handle_async_request(self, request: Request) -> Response: ...

class HTTPTransport(BaseTransport):
    def __init__(self, *, retries: int = ..., **kwargs: Any) -> None: ...

class AsyncHTTPTransport(AsyncBaseTransport):
    def __init__(self, *, retries: int = ..., **kwargs: Any) -> None: ...

class MockTransport(BaseTransport, AsyncBaseTransport):
    def __init__(
        self,
        handler: Callable[[Request], Response] | Callable[[Request], Any],
    ) -> None: ...

class ASGITransport(AsyncBaseTransport):
    def __init__(self, app: Any, **kwargs: Any) -> None: ...

class WSGITransport(BaseTransport):
    def __init__(self, app: Any, **kwargs: Any) -> None: ...

class Client:
    def __init__(
        self,
        *,
        base_url: URLTypes = ...,
        headers: HeaderTypes | None = ...,
        cookies: CookieTypes | None = ...,
        params: QueryParamTypes | None = ...,
        timeout: TimeoutTypes | UseClientDefault = ...,
        limits: Limits = ...,
        transport: BaseTransport | None = ...,
        follow_redirects: bool = ...,
        **kwargs: Any,
    ) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = ...,
        exc_value: BaseException | None = ...,
        traceback: types.TracebackType | None = ...,
    ) -> None: ...
    @property
    def headers(self) -> Headers: ...
    @property
    def cookies(self) -> Cookies: ...
    @property
    def is_closed(self) -> bool: ...
    @property
    def base_url(self) -> URL: ...
    def send(
        self, request: Request, *, stream: bool = ..., **kwargs: Any
    ) -> Response: ...
    def build_request(self, method: str, url: URLTypes, **kwargs: Any) -> Request: ...
    def request(
        self,
        method: str,
        url: URLTypes,
        *,
        content: RequestContent | None = ...,
        data: RequestData | None = ...,
        files: RequestFiles | None = ...,
        json: Any = ...,
        params: QueryParamTypes | None = ...,
        headers: HeaderTypes | None = ...,
        cookies: CookieTypes | None = ...,
        auth: AuthTypes | UseClientDefault | None = ...,
        follow_redirects: bool | UseClientDefault = ...,
        timeout: TimeoutTypes | UseClientDefault = ...,
        extensions: RequestExtensions | None = ...,
    ) -> Response: ...
    def get(
        self,
        url: URLTypes,
        *,
        params: QueryParamTypes | None = ...,
        headers: HeaderTypes | None = ...,
        cookies: CookieTypes | None = ...,
        auth: AuthTypes | UseClientDefault | None = ...,
        follow_redirects: bool | UseClientDefault = ...,
        timeout: TimeoutTypes | UseClientDefault = ...,
        extensions: RequestExtensions | None = ...,
    ) -> Response: ...
    def post(
        self,
        url: URLTypes,
        *,
        content: RequestContent | None = ...,
        data: RequestData | None = ...,
        files: RequestFiles | None = ...,
        json: Any = ...,
        params: QueryParamTypes | None = ...,
        headers: HeaderTypes | None = ...,
        cookies: CookieTypes | None = ...,
        auth: AuthTypes | UseClientDefault | None = ...,
        follow_redirects: bool | UseClientDefault = ...,
        timeout: TimeoutTypes | UseClientDefault = ...,
        extensions: RequestExtensions | None = ...,
    ) -> Response: ...
    def put(
        self,
        url: URLTypes,
        *,
        content: RequestContent | None = ...,
        data: RequestData | None = ...,
        files: RequestFiles | None = ...,
        json: Any = ...,
        params: QueryParamTypes | None = ...,
        headers: HeaderTypes | None = ...,
        cookies: CookieTypes | None = ...,
        auth: AuthTypes | UseClientDefault | None = ...,
        follow_redirects: bool | UseClientDefault = ...,
        timeout: TimeoutTypes | UseClientDefault = ...,
        extensions: RequestExtensions | None = ...,
    ) -> Response: ...
    def patch(
        self,
        url: URLTypes,
        *,
        content: RequestContent | None = ...,
        data: RequestData | None = ...,
        files: RequestFiles | None = ...,
        json: Any = ...,
        params: QueryParamTypes | None = ...,
        headers: HeaderTypes | None = ...,
        cookies: CookieTypes | None = ...,
        auth: AuthTypes | UseClientDefault | None = ...,
        follow_redirects: bool | UseClientDefault = ...,
        timeout: TimeoutTypes | UseClientDefault = ...,
        extensions: RequestExtensions | None = ...,
    ) -> Response: ...
    def delete(
        self,
        url: URLTypes,
        *,
        params: QueryParamTypes | None = ...,
        headers: HeaderTypes | None = ...,
        cookies: CookieTypes | None = ...,
        auth: AuthTypes | UseClientDefault | None = ...,
        follow_redirects: bool | UseClientDefault = ...,
        timeout: TimeoutTypes | UseClientDefault = ...,
        extensions: RequestExtensions | None = ...,
    ) -> Response: ...
    def head(
        self,
        url: URLTypes,
        *,
        params: QueryParamTypes | None = ...,
        headers: HeaderTypes | None = ...,
        cookies: CookieTypes | None = ...,
        auth: AuthTypes | UseClientDefault | None = ...,
        follow_redirects: bool | UseClientDefault = ...,
        timeout: TimeoutTypes | UseClientDefault = ...,
        extensions: RequestExtensions | None = ...,
    ) -> Response: ...
    def options(
        self,
        url: URLTypes,
        *,
        params: QueryParamTypes | None = ...,
        headers: HeaderTypes | None = ...,
        cookies: CookieTypes | None = ...,
        auth: AuthTypes | UseClientDefault | None = ...,
        follow_redirects: bool | UseClientDefault = ...,
        timeout: TimeoutTypes | UseClientDefault = ...,
        extensions: RequestExtensions | None = ...,
    ) -> Response: ...
    def stream(
        self, method: str, url: URLTypes, **kwargs: Any
    ) -> _StreamContextManager: ...
    def close(self) -> None: ...

class _StreamContextManager:
    def __enter__(self) -> Response: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None = ...,
        exc_value: BaseException | None = ...,
        traceback: types.TracebackType | None = ...,
    ) -> None: ...

class _AsyncStreamContextManager:
    async def __aenter__(self) -> Response: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None = ...,
        exc_value: BaseException | None = ...,
        traceback: types.TracebackType | None = ...,
    ) -> None: ...

class AsyncClient:
    def __init__(
        self,
        *,
        base_url: URLTypes = ...,
        headers: HeaderTypes | None = ...,
        cookies: CookieTypes | None = ...,
        params: QueryParamTypes | None = ...,
        timeout: TimeoutTypes | UseClientDefault = ...,
        limits: Limits = ...,
        transport: AsyncBaseTransport | None = ...,
        follow_redirects: bool = ...,
        **kwargs: Any,
    ) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None = ...,
        exc_value: BaseException | None = ...,
        traceback: types.TracebackType | None = ...,
    ) -> None: ...
    @property
    def headers(self) -> Headers: ...
    @property
    def cookies(self) -> Cookies: ...
    @property
    def is_closed(self) -> bool: ...
    async def request(self, method: str, url: URLTypes, **kwargs: Any) -> Response: ...
    async def get(self, url: URLTypes, **kwargs: Any) -> Response: ...
    async def post(self, url: URLTypes, **kwargs: Any) -> Response: ...
    async def put(self, url: URLTypes, **kwargs: Any) -> Response: ...
    async def patch(self, url: URLTypes, **kwargs: Any) -> Response: ...
    async def delete(self, url: URLTypes, **kwargs: Any) -> Response: ...
    async def send(
        self, request: Request, *, stream: bool = ..., **kwargs: Any
    ) -> Response: ...
    def stream(
        self, method: str, url: URLTypes, **kwargs: Any
    ) -> _AsyncStreamContextManager: ...
    def build_request(self, method: str, url: URLTypes, **kwargs: Any) -> Request: ...
    async def aclose(self) -> None: ...

class HTTPError(Exception):
    def __init__(self, message: str) -> None: ...
    @property
    def request(self) -> Request: ...

class TransportError(HTTPError): ...
class TimeoutException(TransportError): ...
class ConnectTimeout(TimeoutException): ...
class ReadTimeout(TimeoutException): ...
class WriteTimeout(TimeoutException): ...
class PoolTimeout(TimeoutException): ...
class NetworkError(TransportError): ...
class ConnectError(NetworkError): ...
class ReadError(NetworkError): ...
class WriteError(NetworkError): ...
class CloseError(NetworkError): ...
class ProtocolError(TransportError): ...
class LocalProtocolError(ProtocolError): ...
class RemoteProtocolError(ProtocolError): ...
class ProxyError(TransportError): ...
class UnsupportedProtocol(TransportError): ...
class DecodingError(HTTPError): ...
class TooManyRedirects(HTTPError): ...

class HTTPStatusError(HTTPError):
    def __init__(
        self, message: str, *, request: Request, response: Response
    ) -> None: ...
    @property
    def response(self) -> Response: ...

class InvalidURL(Exception): ...
class CookieConflict(Exception): ...
class StreamError(RuntimeError): ...
class StreamConsumed(StreamError): ...
class StreamClosed(StreamError): ...

class ResponseNotRead(StreamError):
    def __init__(self) -> None: ...

class RequestNotRead(StreamError): ...

def request(method: str, url: URLTypes, **kwargs: Any) -> Response: ...
def get(url: URLTypes, **kwargs: Any) -> Response: ...
def post(url: URLTypes, **kwargs: Any) -> Response: ...
def put(url: URLTypes, **kwargs: Any) -> Response: ...
def patch(url: URLTypes, **kwargs: Any) -> Response: ...
def delete(url: URLTypes, **kwargs: Any) -> Response: ...
def head(url: URLTypes, **kwargs: Any) -> Response: ...
def options(url: URLTypes, **kwargs: Any) -> Response: ...
def stream(method: str, url: URLTypes, **kwargs: Any) -> _StreamContextManager: ...
