// Generate the typed client's types and the field-type map from the committed
// schema, src/api/openapi.json, into src/api/generated/ (not committed).
//
// The npm scripts that need them (dev, build, test, typecheck) run this first, so
// the generated files always match the committed schema.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import openapiTS, { astToString } from "openapi-typescript";

type Schema = { [key: string]: unknown };
type OpenAPI = {
  paths: { [path: string]: { [verb: string]: unknown } };
  components: { schemas: { [name: string]: Schema } };
};

const api = new URL("../src/api/", import.meta.url);
const generated = new URL("generated/", api);
const openapi = JSON.parse(
  readFileSync(new URL("openapi.json", api), "utf8"),
) as OpenAPI;
const header = "// Generated by scripts/codegen.ts from src/api/openapi.json. Do not edit.\n";

mkdirSync(generated, { recursive: true });
writeFileSync(new URL("schema.ts", generated), header + (await clientTypes(openapi)));
writeFileSync(new URL("fields.ts", generated), header + fieldTypeMap(openapi));

/**
 * The `paths` and `components` types openapi-fetch checks every call against.
 *
 * `defaultNonNullable: false` keeps a property with a server default optional in
 * request bodies; the default (true) makes `reason` and `mode` required on every
 * field write. A schema that refers to itself (the JSON value types) is replaced
 * by `{}`, which generates `unknown`: generated as is, it collapses to `any`,
 * and every body holding one (the create body) stops being checked. The output
 * is `schema.ts`, not `.d.ts`, so `tsc` checks it despite `skipLibCheck` and
 * reports any recursion this misses instead of silently typing it `any`.
 */
async function clientTypes(openapi: OpenAPI): Promise<string> {
  const schemas = Object.fromEntries(
    Object.entries(openapi.components.schemas).map(([name, schema]) => [
      name,
      JSON.stringify(schema).includes(`"#/components/schemas/${name}"`) ? {} : schema,
    ]),
  );
  const nodes = await openapiTS(
    JSON.stringify({ ...openapi, components: { ...openapi.components, schemas } }),
    { defaultNonNullable: false, silent: true },
  );
  return astToString(nodes);
}

/**
 * Every editable field, by route owner (`inquiries` for fields every kind has, a
 * lowercase kind otherwise), with its value type from its `PUT` body.
 *
 * A field is editable exactly when it has a `PUT /api/<owner>/{target_id}/<field>`
 * route. `PATCH` adds or removes one list element; `DELETE` clears the field.
 */
function fieldTypeMap(openapi: OpenAPI): string {
  const owners: { [owner: string]: { [field: string]: unknown } } = {};
  for (const [path, verbs] of Object.entries(openapi.paths).sort()) {
    const match = /^\/api\/(\w+)\/\{target_id\}\/(\w+)$/.exec(path);
    if (!match || !("put" in verbs)) continue;
    const [, owner, field] = match;
    const body = resolve(openapi, requestBody(verbs.put));
    const properties = body.properties as { value: Schema };
    (owners[owner] ??= {})[field] = {
      path,
      value: valueType(openapi, properties.value),
      patch: "patch" in verbs,
      delete: "delete" in verbs,
    };
  }
  return `export const FIELD_ROUTES = ${JSON.stringify(owners, null, 2)} as const;\n`;
}

/** A value's JSON type, without `null`: clearing a field is a `DELETE`. */
function valueType(openapi: OpenAPI, schema: Schema): Schema {
  const resolved = resolve(openapi, schema);
  const variants = (resolved.anyOf as Schema[] | undefined)?.filter(
    (variant) => variant.type !== "null",
  );
  if (variants) {
    if (variants.length !== 1) throw new Error(`Ambiguous field value: ${JSON.stringify(schema)}`);
    return valueType(openapi, variants[0]);
  }
  const type = resolved.type as string;
  return {
    type,
    ...(typeof resolved.format === "string" && { format: resolved.format }),
    ...(type === "array" && { items: valueType(openapi, resolved.items as Schema) }),
  };
}

function requestBody(operation: unknown): Schema {
  const body = (operation as { requestBody: { content: { "application/json": { schema: Schema } } } })
    .requestBody;
  return body.content["application/json"].schema;
}

function resolve(openapi: OpenAPI, schema: Schema): Schema {
  const ref = schema.$ref;
  if (typeof ref !== "string") return schema;
  return resolve(openapi, openapi.components.schemas[ref.split("/").pop()!]);
}
