from collections.abc import Iterator
from typing import Self, final, overload
from typing_extensions import TypeVar

_T = TypeVar("_T")
_Record = TypeVar("_Record", bound=Record, default=Record)

# House override of asyncpg-stubs: a column value is whatever the query
# returned, which the stub cannot know. Upstream says ``Any`` so every read is
# unchecked; ``object`` makes the caller's ``isinstance`` the narrowing.
class Record:
    @overload
    def get(self, key: str) -> object | None: ...
    @overload
    def get(self, key: str, default: _T) -> object | _T: ...
    def items(self) -> Iterator[tuple[str, object]]: ...
    def keys(self) -> Iterator[str]: ...
    def values(self) -> Iterator[object]: ...
    @overload
    def __getitem__(self, index: str) -> object: ...
    @overload
    def __getitem__(self, index: int) -> object: ...
    @overload
    def __getitem__(self, index: slice) -> tuple[object, ...]: ...
    def __iter__(self) -> Iterator[object]: ...
    def __contains__(self, x: object) -> bool: ...
    def __len__(self) -> int: ...

@final
class RecordDescriptor:
    def make_record(self, desc_type: type[_Record], size: int) -> _Record: ...

@final
class RecordItemsIterator(Iterator[tuple[str, object]]):
    def __length_hint__(self) -> int: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> tuple[str, object]: ...

@final
class RecordIterator(Iterator[object]):
    def __length_hint__(self) -> int: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> object: ...
