"""Per-field ``PUT`` / ``PATCH`` / ``DELETE`` routes for inquiry fields.

Routes here are generated by iterating ``inquiry_field_routes``, the
single API definition derived from the ``Annotated[T, ColumnSpec(...)]``
column declarations in ``types/inquiries.py``. This module owns only the
handler bodies (which Store call each verb makes); the wire table decides
which verbs exist on which field with which value type, so the server
can't drift from the client or the docs.

The route factory binds ``FieldSet[T]`` / ``FieldOp[T]`` per field, so
the HTTP boundary validates each value against its real column type and
returns 422 (and an OpenAPI schema) for a bad value.
"""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from typing import Annotated, Literal, cast

import uuid

from fastapi import APIRouter, Depends, HTTPException, Request

from trackinizer.lib.custom_json import MutableJSON
from trackinizer.server.api._deps import get_store
from trackinizer.server.auth import (
    AuthIdentity,
    assert_account_active,
    require_role,
)
from trackinizer.server.store.core import Store
from trackinizer.types.cost import Cost
from trackinizer.types.inquiries import Belief, Inquiry
from trackinizer.wire.bodies import (
    ActorMixin,
    FieldMutation,
    FieldOp,
    FieldSet,
)
from trackinizer.wire.routes import (
    InquiryFieldRoute,
    inquiry_field_path,
    inquiry_field_routes,
)


router = APIRouter()

type _CostAxis = Literal["agent_usd", "resource_usd"]


def _actor_of(body: ActorMixin, identity: AuthIdentity) -> str:
    """Pick the audit actor: the body override, else the caller's email."""
    return body.actor or identity.email


def _mutation_response(
    target_id: uuid.UUID, change_id: uuid.UUID | None
) -> MutableJSON:
    """Build the ``{id, change_id}`` mutation response.

    ``change_id`` is ``None`` for a no-op: the field already held the
    target value, so no ``change_log`` row was written.
    """
    return {
        "id": str(target_id),
        "change_id": None if change_id is None else str(change_id),
    }


def _make_put(route: InquiryFieldRoute) -> Callable[..., Awaitable[MutableJSON]]:
    """Build the typed ``PUT`` handler that sets one field."""

    async def handler(
        target_id: uuid.UUID,
        body: FieldSet[object],
        request: Request,
        identity: Annotated[AuthIdentity, Depends(require_role("writer"))],
    ) -> MutableJSON:
        store = get_store(request)
        if body.mode == "cas":
            change_id = await _run_compare_and_set(
                route, target_id, body, store, identity
            )
        else:
            change_id = await _set_value(
                route, target_id, body.value, body, store, identity=identity
            )
        return _mutation_response(target_id, change_id)

    handler.__name__ = f"set_{route.column}_route"
    handler.__qualname__ = handler.__name__
    handler.__annotations__["body"] = FieldSet[route.value_type]  # ty: ignore[invalid-type-form] -- runtime column type parameterizes the generic body; FastAPI reads it from __annotations__ at registration.
    return handler


def _make_patch(route: InquiryFieldRoute) -> Callable[..., Awaitable[MutableJSON]]:
    """Build the typed ``PATCH`` handler for one field."""

    async def handler(
        target_id: uuid.UUID,
        body: FieldOp[object],
        request: Request,
        identity: Annotated[AuthIdentity, Depends(require_role("writer"))],
    ) -> MutableJSON:
        store = get_store(request)
        change_id = await _run_patch(route, target_id, body, store, identity)
        return _mutation_response(target_id, change_id)

    handler.__name__ = f"patch_{route.column}_route"
    handler.__qualname__ = handler.__name__
    handler.__annotations__["body"] = FieldOp[route.element_type]  # ty: ignore[invalid-type-form] -- runtime element type parameterizes the generic body; FastAPI reads it from __annotations__ at registration.
    return handler


def _make_delete(route: InquiryFieldRoute) -> Callable[..., Awaitable[MutableJSON]]:
    """Build the ``DELETE`` handler that unsets one field."""

    async def handler(
        target_id: uuid.UUID,
        body: FieldMutation,
        request: Request,
        identity: Annotated[AuthIdentity, Depends(require_role("writer"))],
    ) -> MutableJSON:
        store = get_store(request)
        change_id = await _clear_value(route, target_id, body, store, identity)
        return _mutation_response(target_id, change_id)

    handler.__name__ = f"unset_{route.column}_route"
    handler.__qualname__ = handler.__name__
    return handler


for _route in inquiry_field_routes():
    _path = inquiry_field_path(_route.column)
    if _route.put:
        router.put(_path)(_make_put(_route))
    if _route.delete:
        router.delete(_path)(_make_delete(_route))
    if _route.patch:
        router.patch(_path)(_make_patch(_route))


async def _set_value(
    route: InquiryFieldRoute,
    target_id: uuid.UUID,
    value: object,
    body: ActorMixin,
    store: Store,
    *,
    identity: AuthIdentity,
) -> uuid.UUID | None:
    """Execute a blind ``PUT`` overwrite; return the change id, or ``None`` for a no-op.

    Cost axes overwrite through ``Store.set_cost_axis``. Every other field
    forwards ``value`` positionally to its ``set_<column>`` method.
    """
    actor = _actor_of(body, identity)
    reason = cast(FieldSet[object], body).reason
    # ``account`` is the one column whose value must name an active user; the
    # active-user rule is an auth concern enforced here at the route, mirroring
    # the submit path. The Store guarantees only that the column stays
    # non-NULL (no DELETE route, since ``account`` is required).
    if route.column == "account":
        await assert_account_active(store.engine, cast(str, value))
    if route.cost_axis is not None:
        return await store.set_cost_axis(
            target_id,
            cast(_CostAxis, route.cost_axis),
            cast(float, value),
            api_key_id=identity.api_key_id,
            actor=actor,
            reason=reason,
        )
    method = cast(_SetterMethod, getattr(store, cast(str, route.set_method)))
    extra = {"reason": reason} if route.supports_reason else {}
    return await method(
        target_id, value, api_key_id=identity.api_key_id, actor=actor, **extra
    )


async def _clear_value(
    route: InquiryFieldRoute,
    target_id: uuid.UUID,
    body: FieldMutation,
    store: Store,
    identity: AuthIdentity,
) -> uuid.UUID | None:
    """Execute a ``DELETE`` (unset): cost axes clear to 0, other fields to NULL."""
    if route.cost_axis is not None:
        return await store.set_cost_axis(
            target_id,
            cast(_CostAxis, route.cost_axis),
            0.0,
            api_key_id=identity.api_key_id,
            actor=_actor_of(body, identity),
            reason=body.reason,
        )
    return await _set_value(route, target_id, None, body, store, identity=identity)


async def _run_compare_and_set(
    route: InquiryFieldRoute,
    target_id: uuid.UUID,
    body: FieldSet[object],
    store: Store,
    identity: AuthIdentity,
) -> uuid.UUID | None:
    """Execute a compare-and-set ``PUT`` on ``status`` or ``judgement``."""
    if not route.compare_and_set:
        raise HTTPException(
            status_code=400,
            detail=f"expected is not valid for field {route.column!r}",
        )
    actor = _actor_of(body, identity)
    if route.column == "status":
        return await store.transition_status(
            target_id,
            expected_from=cast(Inquiry.Status, body.expected),
            to=cast(Inquiry.Status, body.value),
            api_key_id=identity.api_key_id,
            actor=actor,
            reason=body.reason,
        )
    if route.column == "judgement":
        return await store.transition_judgement(
            target_id,
            expected_from=cast("Belief.Judgement | None", body.expected),
            to=cast("Belief.Judgement | None", body.value),
            api_key_id=identity.api_key_id,
            actor=actor,
            reason=body.reason,
        )
    # ``compare_and_set`` gated entry above, but each CAS column needs its own
    # named transition method; a new CAS column without a branch here would
    # silently route to the wrong field. Fail loudly instead.
    raise HTTPException(
        status_code=500,
        detail=f"no compare-and-set transition wired for field {route.column!r}",
    )


async def _run_patch(
    route: InquiryFieldRoute,
    target_id: uuid.UUID,
    body: FieldOp[object],
    store: Store,
    identity: AuthIdentity,
) -> uuid.UUID | None:
    """Execute a ``PATCH``: a numeric cost delta or a list add/sub."""
    actor = _actor_of(body, identity)
    # Cost axes route through add_cost as a signed Cost delta, not a named
    # add_<stem> setter, so they carry no add_method/sub_method; handle
    # them before the list-method dispatch.
    if route.cost_axis is not None:
        amount = cast(float, body.value) * (1 if body.op == "add" else -1)
        return await store.add_cost(
            target_id,
            Cost(**{route.cost_axis: amount}),
            api_key_id=identity.api_key_id,
            actor=actor,
            reason=body.reason,
        )
    method_name = route.add_method if body.op == "add" else route.sub_method
    if method_name is None:
        raise HTTPException(
            status_code=405,
            detail=f"PATCH op={body.op!r} is not valid for field {route.column!r}",
        )
    element = cast(_ElementMethod, getattr(store, method_name))
    return await element(
        target_id, body.value, api_key_id=identity.api_key_id, actor=actor
    )


_SetterMethod = Callable[..., Awaitable["uuid.UUID | None"]]
_ElementMethod = Callable[..., Awaitable["uuid.UUID | None"]]
